steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: vertical
      remove_redundant: true

columns: 80
newline: lf

language_extensions:
  - NoImplicitPrelude
  - BlockArguments
  - DataKinds
  - DeriveFunctor
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedLabels
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
